// Export utilities for tasks

export const exportAsMarkdown = (task) => {
  return `# ${task.goal}

**Template:** ${task.template}  
**Target Users:** ${task.users}  
**Constraints:** ${task.constraints}  
**Created:** ${new Date(task.createdAt).toLocaleString()}

---

## User Stories (${task.userStories.length})

${task.userStories.map((story, idx) => `${idx + 1}. ${story.story}`).join('\n')}

---

## Engineering Tasks (${task.engineeringTasks.length})

${task.engineeringTasks.map((item, idx) => `- [ ] ${item.task}`).join('\n')}

---

## Risks & Mitigations (${task.risks.length})

${task.risks.map((risk, idx) => `### Risk ${idx + 1}: ${risk.risk}
**Mitigation:** ${risk.mitigation}
`).join('\n')}

---
*Generated by Task Generator*
`;
};

export const exportAsText = (task) => {
  return `${task.goal}
${'='.repeat(task.goal.length)}

Template: ${task.template}
Target Users: ${task.users}
Constraints: ${task.constraints}
Created: ${new Date(task.createdAt).toLocaleString()}

--------------------------------------------------------------------------------

USER STORIES (${task.userStories.length})
${task.userStories.map((story, idx) => `  ${idx + 1}. ${story.story}`).join('\n')}

--------------------------------------------------------------------------------

ENGINEERING TASKS (${task.engineeringTasks.length})
${task.engineeringTasks.map((item, idx) => `  [ ] ${item.task}`).join('\n')}

--------------------------------------------------------------------------------

RISKS & MITIGATIONS (${task.risks.length})
${task.risks.map((risk, idx) => `
  RISK ${idx + 1}: ${risk.risk}
  MITIGATION: ${risk.mitigation}`).join('\n')}

--------------------------------------------------------------------------------
Generated by Task Generator
`;
};

export const exportAllTasksAsMarkdown = (tasks) => {
  return `# Task Generator - All Specs

Generated: ${new Date().toLocaleString()}

---

${tasks.map((task, idx) => `
## ${idx + 1}. ${task.goal}

${exportAsMarkdown(task)}

---
`).join('\n')}
`;
};

export const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy:', err);
    return false;
  }
};

export const downloadAsFile = (content, filename, type = 'text/plain') => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
